version: '3.8'
services:
  web:
    container_name: test_app
    restart: always
    build: .
    command: python ./usr/src/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
