# Generated by Django 4.2.1 on 2023-05-09 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_description_alter_user_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ATTEMPT', 'Attempt')], default='LOGIN', max_length=10)),
            ],
        ),
    ]
